language: python
branches:
  only:
    - master
matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
    - python: "3.7"
      env: TOXENV=cov
      dist: xenial
      after_success: coveralls
cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox coveralls
script: travis_wait 40 tox --develop
